env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
  - warn
  - 4
  linebreak-style:
  - warn
  - unix
  quotes:
  - warn
  - single
  semi:
  - warn
  - never
  brace-style:
  - warn
  - stroustrup
  object-shorthand:
  - warn
  - always
  quote-props:
  - warn
  - always
  array-callback-return:
  - error
  prefer-template:
  - warn
  no-useless-escape:
  - error
  prefer-spread:
  - warn
  prefer-rest-params:
  - warn
  no-case-declarations:
  - error
  no-unneeded-ternary:
  - error
