#!/bin/bash
set -euo pipefail

dockerfile='
FROM registry.fedoraproject.org/fedora-minimal:44
RUN --mount=type=cache,id=rustdev-dnfcache,target=/var/cache/dnf,sharing=locked \
    --mount=type=cache,id=rustdev-dnfhome,target=/var/lib/dnf,sharing=locked \
   dnf -y group install c-development \
&& dnf -y install rust clippy rustfmt rust-analyzer cargo \
&& dnf -y install helix git cmake
'

img='localhost/rustdev'
tag="v2026.05.12"

if ! podman image exists "$img:$tag"; then
    trap 'rm -r -f -- "$tmpdir"' EXIT
    tmpdir="$(mktemp -d)"
    pushd "$tmpdir" >/dev/null
        printf '%s' "$dockerfile" > Dockerfile
        podman build . -t "$img:$tag"
    popd >/dev/null
fi

podman volume create --ignore rustdev-cargohome >/dev/null
# Note that helix is a GNU Store path on my computer.
# podman does not like dereferencing symlinks for --volume.
podman run \
    -it \
    --rm \
    --workdir=/work \
    --volume="${workdir:-"$PWD"}":/work:rw,z \
    --env=COLORTERM="${COLORTERM:-truecolor}" \
    --volume="$(realpath "$XDG_CONFIG_HOME/helix")":/root/.config/helix:ro,z,noexec \
    --env=CARGO_HOME="/root/.cargo" \
    --volume=rustdev-cargohome:/root/.cargo:Z \
    "$img:$tag" "${@:-bash}"
