#!/bin/zsh
find "$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps" \
  -maxdepth 1 \
  -type f \
  -name '*.acf' \
  -exec awk -F '"' '/"appid|name/ { print $4 }' {} + \
| paste - - \
| column --table --separator=$'\t' \
| sort --key=2
