theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
cursorline = true
cursorcolumn = true
auto-pairs = false

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "⸽"

[editor.whitespace.render]
tab = "all"
nbsp = "all"
newline = "all"

[editor.whitespace.characters]
tabpad = "."

[editor.statusline]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal.space]
"i" = ":toggle lsp.display-inlay-hints"
