theme = "solarized_dark"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
cursorline = true
cursorcolumn = true
auto-pairs = false
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"
other-lines = "error"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "⸽"

[editor.whitespace.render]
tab = "all"
nbsp = "all"
newline = "all"

[editor.whitespace.characters]
tabpad = "."

[editor.statusline]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]

[keys.normal.space.i]
i = ":toggle lsp.display-inlay-hints"
c = ":toggle inline-diagnostics.cursor-line hint disable"
e = ":toggle end-of-line-diagnostics hint disable"
o = ":toggle inline-diagnostics.other-lines error disable"
